version: "2.2"
services:
  language-server:
    build:
        context: ./WebSocketLanguageServer
        dockerfile: Dockerfile
    hostname: language-server
    restart: on-failure
    ports:
      - "30000:30000"
      - "3000:3000"

  web-server:
    build:
        context: ./WebSocketClient/UVLPlayground
        dockerfile: Dockerfile
    restart: on-failure
    ports:
     - "8000:80"