version: "2.2"
services:
  codeserver:
    build:
      context: ./code-server
      dockerfile: Dockerfile
    volumes:
      - ~/.local:/home/coder/.local
      - ~/.config:/home/coder/.config
      # - $PWD:/home/coder/project # Map current directory directly in the IDE
    ports:
      - "80:8080"

  language_server:
    build:
      context: ./ls_wrapper
      dockerfile: Dockerfile
    ports:
      - "8080:8080"