version: "2.2"
services:
  language-server:
    build:
        context: ./WebSocketLanguageServer
        dockerfile: Dockerfile
    hostname: language-server
    ports:
      - "30000:30000"

  web-server:
    build:
        context: ./WebSocketClient/UVLPlayground
        dockerfile: Dockerfile
    ports:
     - "8000:80"