version: '3.9'

services:
  webserver:
    build:
        context: ./WebSocketClient
        dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:80"
      
  languageserver:
    build:
        context: ./WebSocketLanguageServer
        dockerfile: Dockerfile
    hostname: language-server
    restart: on-failure
    ports:
      - "30000:30000"
